kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: default
  name: pod-reader
rules:
  - apiGroups: [""] # The API group "" indicates the core API Group.
    resources: ["pods", "services"]
    verbs: ["delete", "get", "watch", "list"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount # May be "User", "Group" or "ServiceAccount"
    name: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: Pod
metadata:
  name: jacky-tools
spec:
  containers:
    - name: jacky-tools
      image: jacky06/jacky-tools:v1
      command: [ "/bin/sh", "-c", "sleep 60000" ]
      env:
        - name: SPECIAL_METADATA_NAME
          valueFrom:
            fieldRef:
             fieldPath: metadata.name
        - name: SPECIAL_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
  restartPolicy: Never
